### PR TITLE
Transparent icons

### PR DESCRIPTION
**Pull request by PoOwAa**
.png files have transparent background from now, solves #14

### CODE REVIEW

**Comment by mcnahum** [comment]
how do we do to have the background of the wifi signal transparent and not black?

**Comment by PoOwAa** [comment]
You just have to git pull the repository to the latest version, it's already merged into master branch. Please let me know if you have any issues! @mcnahum

**Comment by mcnahum** [comment]
Yes, I did that part but the wireless icon still have a black background...small but still there

**Comment by PoOwAa** [comment]
Can you provide a picture about it, please? :)

**Comment by mcnahum** [comment]
of course
--Link removed--

**Comment by PoOwAa** [comment]
Can you check MMM-network-signal/icons folder? It contains several .png files, they should have transparent background. The module simply just puts it in an img tag, so it should be transparent.

**Comment by mcnahum** [comment]
I guess it's my fault... I'm updating with a script who said all was ok ... I run all manually now and it's OK!

Thanks a lot for it

**Pull request merged**
